default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: <%= ENV['SENSE_API_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['SENSE_API_DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['SENSE_API_DATABASE_HOST'] || '127.0.0.1' %>
  port: 3306

development:
  <<: *default
  database: trial_development

test:
  <<: *default
  database: trial_test

production:
  <<: *default
  database: trial_production
